networks:
  api-network:
       external: false
       name: 'api-network'
  cache-network:
       external: false
       name: 'cache-network'
  express-network:
       external: false
       name: 'express-network'

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - 9000:9000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/movies
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS='false'
    networks:
       - api-network
       - cache-network
    depends_on:
      - mongodb
      - redis
  mongodb:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
       - api-network
       - express-network
    volumes: 
      - moviedata:/data/db  

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
       - express-network
    depends_on:
      - mongodb

  redis:
    container_name: redis-caching
    image: redis:alpine
    networks:
      - cache-network

volumes:
   moviedata:
      external: false